# Generated by Django 4.2 on 2023-04-07 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("examapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="date_create",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
